import zhCN from "@/lib/i18n/zh-CN";

export default {
  ...zhCN,
  languageName: "English",
  nav: { main: "Main navigation", myOrders: "My orders", orderLookup: "Order lookup", signIn: "Sign in", accountMenu: "{name}'s account menu", account: "Account", accountSettings: "Account settings", signingOut: "Signing out...", signOut: "Sign out", signOutFailed: "Could not sign out. Please try again.", signedOut: "Signed out." },
  preferences: { language: "Language", theme: "Theme", light: "Light", dark: "Dark" },
  storefront: { fallbackSubtitle: "Choose a product to proceed to checkout", searchProducts: "Search products or keywords", products: "Products", relatedProducts: "{count} matching products", categories: "Product categories", all: "All", stockAvailable: "In stock", stockCount: "{count} in stock", outOfStock: "Out of stock", noProducts: "No products available", noProductsDescription: "Products will appear here once they are published.", contactSupport: "Contact support" },
  auth: {
    login: { tagline: "Digital goods marketplace", headline: "Order, pay, receive,\nall in one flow.", description: "Sign in to view orders, access your history, and manage your account.", createOrder: "Create order", securePayment: "Secure payment", delivery: "Delivery", sslProtected: "This site is protected with SSL encryption", welcomeBack: "Welcome back", email: "Email", password: "Password", signingIn: "Signing in...", signIn: "Sign in", createAccount: "Create account", forgotPassword: "Forgot password", emailInvalid: "Enter a valid email address.", passwordRequired: "Enter your password.", captchaRequired: "Complete the CAPTCHA first.", invalidCredentials: "Incorrect email or password.", requestFailed: "The request failed. Please try again later.", captchaLoadFailed: "The CAPTCHA could not be loaded. Refresh the page and try again.", homeAriaLabel: "Return home" },
    forgotPassword: { title: "Reset password", description: "Enter your registered email and we will send a password reset link.", email: "Email", privacyNotice: "The same result is shown whether or not this email is registered.", sending: "Sending...", sendResetLink: "Send reset link", backToLogin: "Back to sign in", emailInvalid: "Enter a valid email address.", emailTooLong: "Email address is too long.", success: "If this email is registered, a reset link will be sent to it." },
    resetPassword: { title: "Reset password", description: "Enter a new password to finish resetting your password.", password: "New password", confirmPassword: "Confirm new password", resetting: "Resetting...", reset: "Reset password", invalidTitle: "Invalid reset link", invalidDescription: "The reset link is missing valid credentials or has expired. Request a new one.", backToForgotPassword: "Back to password recovery", passwordTooShort: "Password must be at least 8 characters.", passwordTooLong: "Password cannot exceed 128 characters.", passwordsMismatch: "Passwords do not match.", invalidOrExpired: "The reset link is invalid or has expired. Request a new one.", success: "Password reset. Sign in again." },
    twoFactor: { title: "Two-factor authentication", description: "Enter the 6-digit code displayed in your authenticator app to continue signing in.", code: "Verification code", placeholder: "6-digit code", verifying: "Verifying...", continue: "Continue sign in", codeInvalid: "Enter a 6-digit code.", codeExpired: "The verification code is invalid or expired.", failed: "Verification could not be completed. Please try again later." },
    signup: { unavailable: "Registration unavailable", notInitialized: "The site has not been initialized yet. Please try again later...", disabled: "Registration is not enabled. Contact support if you need help.", title: "Create account", description: "Create an account to sign in with your email and password.", name: "Display name", email: "Email", password: "Password", confirmPassword: "Confirm password", signingUp: "Creating account...", signUp: "Create account", haveAccount: "Already have an account? Sign in", nameRequired: "Enter a display name.", nameTooLong: "Display name cannot exceed 100 characters.", emailInvalid: "Enter a valid email address.", emailTooLong: "Email address is too long.", passwordTooShort: "Password must be at least 8 characters.", passwordTooLong: "Password cannot exceed 128 characters.", passwordsMismatch: "Passwords do not match.", failed: "Could not create the account. Check your information or try again later.", submitted: "Your registration was submitted. Verify your email before signing in.", requestFailed: "The request failed. Please try again later." },
  },
  common: { requestFailed: "The request failed. Please try again later.", queryFailed: "Lookup failed", loading: "Loading..." },
  productCheckout: {
    defaultCategory: "Product", productDetails: "Product details", purchaseInstructions: "Purchase instructions", currentPrice: "Current price", noPaymentMethod: "No payment method is currently available. Please try again later.", contactEmail: "Contact email", quantity: "Quantity", availableStock: "Available stock: {count}", shippingAddress: "Shipping address", selectSavedAddress: "Select a saved address", selectShippingAddress: "Select shipping address", enterNewAddress: "Enter a new address", clearBrowserAddresses: "Clear addresses saved in this browser", loadingSavedAddresses: "Loading saved addresses...", savingAddress: "Saving...", saveAddress: "Save address", paymentMethod: "Payment method", discountCode: "Discount code", applyingDiscount: "Applying...", applyDiscount: "Apply", originalAmount: "Original amount", appliedDiscount: "Discount {code}", amountDue: "Amount due", buyerNote: "Order note", processingOrder: "Processing...", submitAndPay: "Place order and pay", createFreeOrder: "Create free order", paymentAmountNotice: "The payment amount must exactly match the order amount.", imagePreview: "Image preview", closeImagePreview: "Close image preview", confirmClearAddressesTitle: "Clear saved addresses?", confirmClearAddressesDescription: "This removes all guest addresses saved in this browser and cannot be undone.", cancel: "Cancel", confirmClearAddresses: "Clear addresses", defaultPurchaseNote: "A pending-payment order will be created. After payment succeeds, a notification will be sent to your contact email.", defaultManualDeliveryHint: "After payment, support will process your order as soon as possible.", defaultExpressDeliveryHint: "Enter your delivery information. An administrator will arrange shipping after payment.",
    address: { recipientName: "Recipient", phone: "Phone", country: "Country or region", province: "State or province", city: "City", district: "District", addressLine: "Street address", postalCode: "Postal code", defaultCountry: "China" },
    validation: { recipientNameRequired: "Enter the recipient name", phoneInvalid: "Enter a valid phone number", countryRequired: "Enter a country or region", provinceRequired: "Enter a state or province", cityRequired: "Enter a city", districtRequired: "Enter a district", addressLineRequired: "Enter a street address", postalCodeInvalid: "Enter a valid postal code" },
    discountPreviewFailed: "The discount code could not be verified. Please try again later.", insufficientStock: "Insufficient stock. Adjust the quantity and try again.", applyDiscountFirst: "Apply the discount code first.", orderSubmissionFailed: "The order could not be submitted. Please try again later.", shippingAddressIncomplete: "Complete the shipping address.", addressSaveStorageFailed: "The address could not be saved. Check your browser storage space.", addressSaved: "Address saved.", addressSaveFailed: "The address could not be saved. Please try again later.", clearAddressesFailed: "Saved addresses could not be cleared. Check browser storage permissions.", addressesCleared: "Addresses saved in this browser were cleared.", addressLoadFailed: "Saved addresses could not be loaded. Enter an address for this order.", paymentChannels: { web: "Web/H5", wap: "H5", faceToFace: "In-person", alipay: "Alipay", wxpay: "WeChat Pay" },
  },
  account: {
    title: "Account", description: "View your account profile and manage frequently used delivery addresses.", avatarFallback: "A",
    profile: { title: "Profile", description: "Manage the account name used for purchases and notifications.", nameUnset: "No name set", unchanged: "No changes to save.", saveFailed: "Profile could not be saved. Please try again later.", updated: "Profile updated." },
    email: { title: "Email address", description: "Used for notifications, account recovery, and email/password sign-in.", current: "Current email", verified: "Verified", unverified: "Unverified", unset: "No email set", new: "New email", verificationNotice: "The new email takes effect after verification. It can only be changed once every 24 hours.", sending: "Sending...", resendAfter: "Resend in {seconds} seconds", change: "Change email", sameAsCurrent: "The new email matches your current email.", sendFailedWithLimit: "Verification email could not be sent. The email can only be changed once every 24 hours.", sendFailed: "Verification email could not be sent. Please try again later.", verificationSent: "A verification email was sent to the new address. Complete verification to apply it." },
    password: { title: "Change password", description: "Your current password is required. Other signed-in sessions will be signed out after the change.", current: "Current password", new: "New password", confirm: "Confirm new password", changing: "Changing...", changeFailedInvalid: "Password could not be changed. Check your current password and the new password requirements.", changed: "Password changed. Other signed-in sessions were signed out.", changeFailed: "Password could not be changed. Please try again later." },
    actions: { save: "Save", saving: "Saving...", cancel: "Cancel", delete: "Delete", deleting: "Deleting..." },
    addresses: { title: "Address book", description: "Save frequently used delivery addresses, up to {limit}.", add: "Add address", limitReached: "You have reached the {limit}-address limit. Delete an unused address first.", loading: "Loading address book...", emptyTitle: "No delivery addresses", emptyDescription: "Add an address to use it when purchasing physical products.", addFirst: "Add your first address", defaultBadge: "Default", editAriaLabel: "Edit address", postalCodeValue: "Postal code: {postalCode}", setDefault: "Set as default", editTitle: "Edit address", createTitle: "Add address", editorDescription: "Enter complete recipient information. Fields marked with an asterisk are required.", save: "Save address", deleteTitle: "Delete address?", deleteDescription: "The delivery address for {recipientName} will be deleted. This cannot be undone.", confirmDelete: "Delete address", defaultCountry: "China", loadFailed: "Address book could not be loaded. Please try again later.", limitToast: "The address book can contain up to {limit} addresses.", updated: "Address updated.", created: "Address added.", defaultUpdated: "Default address updated.", deleted: "Address deleted.", invalidForm: "Check the required fields and input format." },
    addressFields: { name: "Name", recipientName: "Recipient", phone: "Phone", country: "Country or region", province: "State or province", city: "City", district: "District", addressLine: "Street address", postalCode: "Postal code", isDefault: "Set as default address" },
    validation: { required: "Enter {label}.", maxLength: "{label} cannot exceed {max} characters.", emailRequired: "Enter an email address.", emailInvalid: "Enter a valid email address.", emailMaxLength: "Email cannot exceed 320 characters.", currentPasswordRequired: "Enter your current password.", newPasswordTooShort: "New password must be at least 8 characters.", newPasswordTooLong: "New password cannot exceed 128 characters.", confirmPasswordRequired: "Confirm your new password.", passwordsMismatch: "New passwords do not match.", phoneInvalid: "Enter a valid phone number.", postalCodeInvalid: "Enter a valid postal code." },
  },
  accountOrders: {
    title: "My orders", description: "Only orders created by the current signed-in account are shown.", lookup: { title: "Find an account order", description: "Use an order number to look up details for an order belonging to this account.", orderNumber: "Order number", placeholder: "ORD...", failed: "Lookup failed", loading: "Searching...", notFound: "No order with that number belongs to this account." }, guestLookup: { title: "Cannot find the order?", description: "For orders placed before signing in, use the order number and order email to look up the guest order.", action: "Find a guest order" }, back: "Back", backAriaLabel: "Return to account order list", detail: { title: "Order details", quantity: "Quantity", amount: "Amount", paymentStatus: "Payment status", deliveryStatus: "Delivery status", deliveryContents: "Delivery contents", awaitingDeliveryTitle: "Awaiting delivery", awaitingDeliveryDescription: "The order is paid and delivery is being processed." }, payment: { goToPayment: "Go to payment", generating: "Generating payment details...", resume: "Resume payment", generateFailed: "Payment details could not be generated. Please try again later.", resumeFailed: "Payment could not be resumed. Please try again later." }, list: { eyebrow: "Select or find an order", title: "Account order list", description: "Only orders created by the current signed-in account are shown. Select one to view details or resume payment.", loading: "Loading orders...", loadFailed: "Loading failed", reload: "Reload", empty: "This account has no orders yet.", truncated: "Only the most recent {limit} account orders are shown." }, status: { pending: "Pending payment", paid: "Paid", delivered: "Delivered", closed: "Closed", failed: "Failed" }, paymentStatus: { unpaid: "Pending payment", paid: "Paid", failed: "Payment failed" }, deliveryStatus: { notDelivered: "Not delivered", delivering: "Delivering", delivered: "Delivered", failed: "Delivery failed" },
  },
} as unknown as typeof zhCN;
