<template>
  <section class="flex w-full flex-col gap-6">
    <AdminPageHeader />
    <div class="flex items-center justify-between gap-2"><Input v-model="search" class="h-9 w-72" placeholder="搜索账号或 API 来源" @keyup.enter="searchAccounts" /><div class="flex gap-2"><Button variant="outline" :disabled="loading" @click="load">刷新</Button><Button @click="openCreate">添加账号</Button></div></div>
    <AdminDataTable :columns="columns" :rows="data.items" row-key="id" empty-text="暂无供应商账号。">
      <template #cell-enabled="{ row }"><Switch :model-value="row.enabled" :disabled="loading" @update:model-value="setEnabled(row, $event)" /></template>
      <template #cell-provider="{ row }">{{ providerLabel(row.provider, row.protocolVersion) }}</template>
      <template #cell-balanceMinor="{ row }">{{ row.balanceMinor === null ? "未同步" : `${availableBalance(row)} ${row.currency}` }}</template>
      <template #cell-healthStatus="{ row }"><Badge :variant="row.healthStatus === 'healthy' ? 'default' : 'secondary'">{{ healthLabel(row.healthStatus) }}</Badge></template>
      <template #actions="{ row }"><Button variant="ghost" size="sm" :disabled="testingId === row.id" @click="test(row)">{{ testingId === row.id ? "测试中..." : "测试连接" }}</Button><Button variant="ghost" size="sm" @click="openEdit(row)">编辑</Button><Button variant="ghost" size="sm" class="text-destructive" @click="remove(row)">删除</Button></template>
      <template #pagination><Pagination :total="data.total" :page="data.page" :page-size="data.pageSize" :page-size-options="[10, 20, 50, 100]" @update:page="changePage" @update:page-size="changePageSize" /></template>
    </AdminDataTable>

    <Dialog v-model:open="dialogOpen"><DialogContent class="max-w-lg"><DialogHeader><DialogTitle>{{ editing ? "编辑供应商账号" : "添加供应商账号" }}</DialogTitle><DialogDescription>{{ editing ? "凭证留空表示保持原凭证；填写完整的新凭证后替换。" : "凭证仅用于连接上游，不会显示原始内容。" }}</DialogDescription></DialogHeader><div class="grid gap-4"><div class="grid gap-2"><Label>供应商类型</Label><Select v-model="form.provider" :disabled="editing"><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="acg">二次元 / ACG</SelectItem><SelectItem value="dujiao_next">独角数卡 Next</SelectItem></SelectContent></Select></div><div v-if="form.provider === 'acg'" class="grid gap-2"><Label>协议版本</Label><Select v-model="form.protocolVersion" :disabled="editing"><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="acg_v3.1.2_plus">异次元（V3.1.2+ 新版）</SelectItem><SelectItem value="acg_v3.1.1">异次元（V3.1.1 之前旧版）</SelectItem></SelectContent></Select></div><div class="grid gap-2"><Label>名称</Label><Input v-model="form.name" /></div><div class="grid gap-2"><Label>API 来源</Label><Input v-model="form.baseUrl" :readonly="editing" /></div><div class="grid gap-3"><div v-if="form.provider === 'acg'" class="grid gap-2"><Label>商户 ID</Label><Input v-model="form.apiId" inputmode="numeric" placeholder="留空表示不修改" /></div><div v-if="form.provider === 'acg'" class="grid gap-2"><Label>商户密钥</Label><Input v-model="form.appKey" type="password" autocomplete="new-password" placeholder="留空表示不修改" /></div><div v-if="form.provider === 'dujiao_next'" class="grid gap-2"><Label>API Key</Label><Input v-model="form.apiKey" autocomplete="off" placeholder="留空表示不修改" /></div><div v-if="form.provider === 'dujiao_next'" class="grid gap-2"><Label>API Secret</Label><Input v-model="form.apiSecret" type="password" autocomplete="new-password" placeholder="留空表示不修改" /></div></div><div class="grid grid-cols-2 gap-3"><div class="grid gap-2"><Label>币种</Label><Input v-model="form.currency" /></div><div class="grid gap-2"><Label>小数位</Label><Input v-model.number="form.currencyDecimals" type="number" min="0" max="8" /></div></div><div v-if="!editing" class="flex items-center gap-2"><Switch v-model:model-value="form.enabled" /><Label>启用账号</Label></div></div><DialogFooter><Button variant="outline" @click="dialogOpen = false">关闭</Button><Button :disabled="saving" @click="save">{{ saving ? "保存中..." : "保存" }}</Button></DialogFooter></DialogContent></Dialog>
  </section>
</template>
<script setup lang="ts">
import { onMounted, reactive, ref } from "vue";
import AdminDataTable, { type AdminTableColumn } from "@/components/admin/AdminDataTable.vue";
import AdminPageHeader from "@/components/admin/AdminPageHeader.vue";
import { Badge } from "@/components/ui/badge"; import { Button } from "@/components/ui/button"; import { Input } from "@/components/ui/input"; import Pagination from "@/components/ui/pagination/Pagination.vue"; import { Label } from "@/components/ui/label"; import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog"; import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"; import { Switch } from "@/components/ui/switch";
import { formatMinorAmount } from "@/lib/payment-utils"; import { runTelefunc } from "@/lib/telefunc-client"; import { onDeleteSupplierAccount, onListSupplierAccounts, onSaveSupplierAccount, onSetSupplierAccountEnabled, onTestSupplierAccount } from "@/server/supplier/admin.telefunc";
type Data = Awaited<ReturnType<typeof onListSupplierAccounts>>; type Account = Data["items"][number];
const columns: AdminTableColumn<Account>[] = [{ key: "enabled", label: "启用" }, { key: "name", label: "名称" }, { key: "provider", label: "API 来源" }, { key: "balanceMinor", label: "可用余额" }, { key: "healthStatus", label: "健康状态" }];
const data = reactive<Data>({ items: [], total: 0, page: 1, pageSize: 20 }); const search = ref(""); const loading = ref(false); const saving = ref(false); const dialogOpen = ref(false); const testingId = ref<string | null>(null); const editing = ref(false);
const form = reactive({ id: undefined as string | undefined, provider: "acg" as "acg" | "dujiao_next", protocolVersion: "acg_v3.1.2_plus" as "acg_v3.1.2_plus" | "acg_v3.1.1" | "dujiao_next_v1", name: "", baseUrl: "", apiId: "", appKey: "", apiKey: "", apiSecret: "", credentialsConfigured: false, currency: "CNY", currencyDecimals: 2, reserveBalanceMinor: "0", lowBalanceMinor: "0", maxOrderCostMinor: null as string | null, enabled: false });

onMounted(load);
async function load() { loading.value = true; try { Object.assign(data, await runTelefunc(() => onListSupplierAccounts({ search: search.value, page: data.page, pageSize: data.pageSize }), { errorMessage: "读取供应商账号失败，请稍后重试。" })); } finally { loading.value = false; } }
function searchAccounts() { data.page = 1; void load(); } function changePage(page: number) { data.page = page; void load(); } function changePageSize(size: number) { data.pageSize = size; data.page = 1; void load(); }
function openCreate() { editing.value = false; Object.assign(form, { id: undefined, provider: "acg", protocolVersion: "acg_v3.1.2_plus", name: "", baseUrl: "", apiId: "", appKey: "", apiKey: "", apiSecret: "", credentialsConfigured: false, currency: "CNY", currencyDecimals: 2, reserveBalanceMinor: "0", lowBalanceMinor: "0", maxOrderCostMinor: null, enabled: false }); dialogOpen.value = true; }
function openEdit(row: Account) { editing.value = true; Object.assign(form, { id: row.id, provider: row.provider, protocolVersion: row.protocolVersion === "3.5.5-v4" ? "acg_v3.1.2_plus" : row.protocolVersion, name: row.name, baseUrl: row.baseUrl, credentialsConfigured: row.credentialsConfigured, currency: row.currency, currencyDecimals: row.currencyDecimals }); dialogOpen.value = true; }
async function save() { const credentials = form.provider === "acg" ? (form.apiId.trim() || form.appKey ? { apiId: form.apiId.trim(), appKey: form.appKey } : undefined) : (form.apiKey.trim() || form.apiSecret ? { apiKey: form.apiKey.trim(), apiSecret: form.apiSecret } : undefined); if (!editing.value && !credentials) return; if (credentials && ((form.provider === "acg" && (!form.apiId.trim() || !form.appKey)) || (form.provider === "dujiao_next" && (!form.apiKey.trim() || !form.apiSecret)))) return; saving.value = true; try { if (editing.value) await runTelefunc(() => onSaveSupplierAccount({ id: form.id!, name: form.name, baseUrl: form.baseUrl, currency: form.currency, currencyDecimals: form.currencyDecimals, ...(credentials ? { credentials } : {}) }), { successMessage: "供应商账号已更新。" }); else await runTelefunc(() => onSaveSupplierAccount({ provider: form.provider, protocolVersion: form.provider === "dujiao_next" ? "dujiao_next_v1" : form.protocolVersion, name: form.name, baseUrl: form.baseUrl, currency: form.currency, currencyDecimals: form.currencyDecimals, reserveBalanceMinor: form.reserveBalanceMinor, lowBalanceMinor: form.lowBalanceMinor, maxOrderCostMinor: form.maxOrderCostMinor, enabled: form.enabled, credentials }), { successMessage: "供应商账号已保存。" }); dialogOpen.value = false; await load(); } finally { saving.value = false; } }
async function setEnabled(row: Account, enabled: boolean) { await runTelefunc(() => onSetSupplierAccountEnabled({ id: row.id, enabled }), { successMessage: enabled ? "账号已启用。" : "账号已停用。" }); await load(); }
async function remove(row: Account) { if (!confirm(`确认删除供应商账号“${row.name}”？`)) return; await runTelefunc(() => onDeleteSupplierAccount({ id: row.id }), { successMessage: "供应商账号已删除或停用。" }); await load(); }
async function test(row: Account) { testingId.value = row.id; try { await runTelefunc(() => onTestSupplierAccount({ id: row.id }), { successMessage: "连接测试成功。" }); await load(); } finally { testingId.value = null; } }
function providerLabel(provider: Account["provider"], version: Account["protocolVersion"]) { return provider === "acg" ? `二次元 / ACG（${version === "acg_v3.1.1" ? "V3.1.1 之前旧版" : "V3.1.2+ 新版"}）` : "独角数卡 Next"; } function availableBalance(row: Account) { const balance = row.balanceMinor && /^(0|[1-9]\d*)$/.test(row.balanceMinor) ? BigInt(row.balanceMinor) : 0n; const reserved = /^(0|[1-9]\d*)$/.test(row.reserveBalanceMinor) ? BigInt(row.reserveBalanceMinor) : 0n; return formatMinorAmount((balance > reserved ? balance - reserved : 0n).toString(), row.currencyDecimals); } function healthLabel(value: Account["healthStatus"]) { return { unknown: "未测试", healthy: "健康", degraded: "异常", unavailable: "不可用" }[value]; }
</script>
