<template>
  <section class="flex w-full flex-col gap-6">
    <AdminPageHeader />
    <div class="flex flex-wrap items-center justify-between gap-2">
      <div class="flex gap-2">
        <Select v-model="sourceKey" @update:model-value="handleSourceChange"><SelectTrigger class="w-72"><SelectValue placeholder="选择供应商来源" /></SelectTrigger><SelectContent><SelectItem v-for="source in sources" :key="sourceKeyOf(source)" :value="sourceKeyOf(source)">{{ source.name }}</SelectItem></SelectContent></Select>
        <Button :disabled="loading || syncing || !selectedSource" @click="refreshProducts">{{ loading ? '获取中...' : '获取商品' }}</Button>
      </div>
      <div class="flex gap-2"><Button variant="outline" :disabled="!selectedKeys.size || importingKey === 'batch'" @click="importSelected">{{ importingKey === 'batch' ? '批量导入中...' : `批量导入 (${selectedKeys.size})` }}</Button><Button variant="outline" :disabled="syncing || loading || bindingCount === 0" @click="sync">{{ syncing ? `正在同步 ${bindingCount} 个已导入商品...` : bindingCount ? `同步 ${bindingCount} 个已导入商品` : '暂无已导入商品' }}</Button></div>
    </div>
    <div v-if="!sources.length" class="rounded-lg border p-8 text-center text-muted-foreground">请先在供应商账号页面添加并启用账号。</div>
    <div v-else class="rounded-lg border bg-muted/30 px-4 py-3 text-sm text-muted-foreground">已导入并绑定：<span class="font-medium text-foreground">{{ bindingCount }} 个 SKU</span><span v-if="lastSyncedAt"> · 上次同步：{{ lastSyncedAt }}</span><span v-if="lastSyncResult"> · {{ lastSyncResult }}</span><span class="block mt-1">同步会更新库存、供应商参考成本和上游可售状态，不会修改本地售价、名称或详情。</span></div>
    <div v-if="sources.length" class="overflow-x-auto rounded-lg border bg-card">
      <Table>
        <TableHeader><TableRow><TableHead>选择</TableHead><TableHead class="w-80">商品</TableHead><TableHead class="w-80">SKU</TableHead><TableHead>本地商品</TableHead><TableHead>零售价</TableHead><TableHead>会员参考价</TableHead><TableHead>实时拿货价</TableHead><TableHead>库存</TableHead><TableHead class="text-right">操作</TableHead></TableRow></TableHeader>
        <TableBody>
          <template v-for="group in productGroups" :key="group.id">
            <TableRow v-if="group.skus.length === 1">
              <TableCell><input type="checkbox" :checked="selectedKeys.has(group.skus[0]!.key)" aria-label="选择 SKU" @change="toggleSelected(group.skus[0]!.key, ($event.target as HTMLInputElement).checked)" /></TableCell>
              <TableCell class="max-w-80"><span class="block truncate font-medium" :title="group.name">{{ group.name }}</span></TableCell><TableCell class="max-w-80"><span class="block truncate" :title="group.skus[0]!.skuName">{{ group.skus[0]!.skuName }}</span></TableCell><TableCell>{{ group.skus[0]!.localProductName || '未导入' }}</TableCell>
              <TableCell>{{ price(group.skus[0]!.retailPriceMinor ?? group.skus[0]!.costMinor) }}</TableCell><TableCell>{{ group.skus[0]!.memberPriceMinor ? price(group.skus[0]!.memberPriceMinor) : '—' }}</TableCell><TableCell>{{ group.skus[0]!.livePurchasePriceMinor ? price(group.skus[0]!.livePurchasePriceMinor) : '—' }}</TableCell><TableCell>{{ stock(group.skus[0]!.stockQuantity) }}</TableCell>
              <TableCell class="text-right"><Button size="sm" variant="outline" :disabled="Boolean(importingKey) || syncing" @click="importSku(group.skus[0]!)">{{ group.skus[0]!.localProductName ? '更新本地' : '导入本地' }}</Button></TableCell>
            </TableRow>
            <template v-else>
              <TableRow class="bg-muted/20"><TableCell><button class="text-lg" :aria-label="expandedProducts.has(group.id) ? '收起 SKU' : '展开 SKU'" @click="toggleExpanded(group.id)">{{ expandedProducts.has(group.id) ? '▾' : '▸' }}</button></TableCell><TableCell class="max-w-80"><span class="block truncate font-medium" :title="group.name">{{ group.name }}</span><span class="text-xs text-muted-foreground">({{ group.skus.length }} 个 SKU)</span></TableCell><TableCell>—</TableCell><TableCell>{{ group.localProductNames.join('、') || '未导入' }}</TableCell><TableCell>—</TableCell><TableCell>—</TableCell><TableCell>—</TableCell><TableCell>—</TableCell><TableCell class="text-right"><Button size="sm" variant="outline" :disabled="Boolean(importingKey) || syncing" @click="importSku(group.skus[0]!)">{{ group.localProductNames.length ? '更新本地' : '导入本地' }}</Button></TableCell></TableRow>
              <TableRow v-for="row in expandedProducts.has(group.id) ? group.skus : []" :key="row.key"><TableCell><input type="checkbox" :checked="selectedKeys.has(row.key)" aria-label="选择 SKU" @change="toggleSelected(row.key, ($event.target as HTMLInputElement).checked)" /></TableCell><TableCell class="max-w-80 pl-8 text-muted-foreground"><span class="block truncate" :title="group.name">↳ {{ group.name }}</span></TableCell><TableCell class="max-w-80"><span class="block truncate" :title="row.skuName">{{ row.skuName }}</span></TableCell><TableCell>{{ row.localProductName || '未导入' }}</TableCell><TableCell>{{ price(row.retailPriceMinor ?? row.costMinor) }}</TableCell><TableCell>{{ row.memberPriceMinor ? price(row.memberPriceMinor) : '—' }}</TableCell><TableCell>{{ row.livePurchasePriceMinor ? price(row.livePurchasePriceMinor) : '—' }}</TableCell><TableCell>{{ stock(row.stockQuantity) }}</TableCell><TableCell></TableCell></TableRow>
            </template>
          </template>
          <TableRow v-if="!productGroups.length"><TableCell :colspan="9" class="h-28 text-center text-muted-foreground">{{ catalogLoaded ? '暂无上游商品数据。' : '选择渠道后，点击“获取商品”拉取上游目录。' }}</TableCell></TableRow>
        </TableBody>
      </Table>
      <div class="flex items-center justify-between p-3 text-sm"><span>共 {{ totalProducts }} 个商品，第 {{ page }} / {{ totalPages }} 页</span><div class="flex gap-2"><Button variant="outline" size="sm" :disabled="loading || page <= 1" @click="changePage(page - 1)">上一页</Button><Button variant="outline" size="sm" :disabled="loading || page >= totalPages" @click="changePage(page + 1)">下一页</Button></div></div>
    </div>
    <Dialog v-model:open="syncDialogOpen"><DialogContent><DialogHeader><DialogTitle>同步已导入商品</DialogTitle><DialogDescription>将从当前供应商更新已导入的 {{ bindingCount }} 个商品的库存、参考成本、可售状态信息。</DialogDescription></DialogHeader><p class="text-sm text-muted-foreground">不会修改本地售价、商品名称或商品详情。</p><DialogFooter><Button variant="outline" :disabled="syncing" @click="syncDialogOpen = false">取消</Button><Button :disabled="syncing" @click="confirmSync">{{ syncing ? '同步中...' : '开始同步' }}</Button></DialogFooter></DialogContent></Dialog>
    <Dialog v-model:open="markupDialogOpen"><DialogContent><DialogHeader><DialogTitle>设置导入加价</DialogTitle><DialogDescription>请输入导入本地商品时使用的固定加价和比例加价。</DialogDescription></DialogHeader><div class="grid gap-4"><Field><FieldLabel for="fixed-markup-yuan">固定加价（元）</FieldLabel><Input id="fixed-markup-yuan" v-model="fixedMarkupYuan" inputmode="decimal" placeholder="0.00" /><FieldDescription>可填写最多两位小数，例如 1.50。</FieldDescription></Field><Field><FieldLabel for="markup-percent">比例加价（百分比）</FieldLabel><Input id="markup-percent" v-model="markupPercent" inputmode="decimal" placeholder="0" /><FieldDescription>请输入 0 至 100 的百分比。</FieldDescription></Field><p v-if="markupError" class="text-sm text-destructive">{{ markupError }}</p></div><DialogFooter><Button variant="outline" :disabled="Boolean(importingKey)" @click="markupDialogOpen = false">取消</Button><Button :disabled="Boolean(importingKey)" @click="submitMarkup">{{ importingKey ? '导入中...' : '确认导入' }}</Button></DialogFooter></DialogContent></Dialog>
  </section>
</template>
<script setup lang="ts">
import { computed, onMounted, ref } from "vue";
import AdminPageHeader from "@/components/admin/AdminPageHeader.vue";
import { Button } from "@/components/ui/button";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Field, FieldDescription, FieldLabel } from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { formatMinorAmount, parseAmountToCents } from "@/lib/payment-utils";
import { runTelefunc, userErrorMessage } from "@/lib/telefunc-client";
import { onGetSupplierSourceBindingCount, onListSupplierProducts, onListSupplierSources, onSyncSupplierSource } from "@/server/supplier/catalog.telefunc";
import { onImportSupplierProduct } from "@/server/supplier/import.telefunc";
type Source = Awaited<ReturnType<typeof onListSupplierSources>>[number]; type CatalogPage = Awaited<ReturnType<typeof onListSupplierProducts>>; type UpstreamProduct = CatalogPage["products"][number]; type Product = UpstreamProduct & { skuId: string; skuName: string; costMinor: string; retailPriceMinor?: string; memberPriceMinor?: string; livePurchasePriceMinor?: string; stockQuantity: number; active: boolean; localProductName: string | null; key: string };
type ProductGroup = { id: string; name: string; skus: Product[]; localProductNames: string[] };
const sources = ref<Source[]>([]); const products = ref<Product[]>([]); const expandedProducts = ref(new Set<string>()); const selectedKeys = ref(new Set<string>()); const sourceKey = ref(""); const page = ref(1); const totalProducts = ref(0); const pageSize = 50; const loading = ref(false); const catalogLoaded = ref(false); const syncing = ref(false); const bindingCount = ref(0); const lastSyncedAt = ref(""); const lastSyncResult = ref(""); const syncDialogOpen = ref(false); const importingKey = ref(""); const error = ref<string | null>(null); const markupDialogOpen = ref(false); const markupRows = ref<Product[]>([]); const fixedMarkupYuan = ref("0"); const markupPercent = ref("0"); const markupError = ref<string | null>(null); const catalogRequestId = ref(0);
const selectedSource = computed(() => sources.value.find((item) => sourceKeyOf(item) === sourceKey.value)); const totalPages = computed(() => Math.max(1, Math.ceil(totalProducts.value / pageSize)));
const productGroups = computed<ProductGroup[]>(() => { const groups = new Map<string, ProductGroup>(); for (const sku of products.value) { const group = groups.get(sku.id) ?? { id: sku.id, name: sku.name, skus: [], localProductNames: [] }; group.skus.push(sku); if (sku.localProductName && !group.localProductNames.includes(sku.localProductName)) group.localProductNames.push(sku.localProductName); groups.set(sku.id, group); } return [...groups.values()]; });
function sourceKeyOf(source: Source) { return `${source.provider}|${source.normalizedApiOrigin}|${source.protocolVersion}`; } function price(value: string) { return `${formatMinorAmount(value, selectedSource.value?.currencyDecimals ?? 2)} ${selectedSource.value?.currency ?? "CNY"}`; } function stock(value: number) { return value >= 2147483647 ? "不限" : String(value); } function refreshProducts() { page.value = 1; void loadProducts(true); } function sourceInput(source: Source) { return { provider: source.provider, normalizedApiOrigin: source.normalizedApiOrigin, protocolVersion: source.protocolVersion }; } async function loadBindingCount() { const source = selectedSource.value; if (!source) return; bindingCount.value = (await runTelefunc(() => onGetSupplierSourceBindingCount(sourceInput(source)), { notifyError: false })).bindingCount; } async function handleSourceChange() { catalogRequestId.value += 1; products.value = []; selectedKeys.value = new Set(); expandedProducts.value = new Set(); page.value = 1; totalProducts.value = 0; catalogLoaded.value = false; bindingCount.value = 0; lastSyncedAt.value = ""; lastSyncResult.value = ""; error.value = null; await loadBindingCount(); } function toggleExpanded(id: string) { const next = new Set(expandedProducts.value); if (next.has(id)) next.delete(id); else next.add(id); expandedProducts.value = next; } function changePage(nextPage: number) { page.value = nextPage; void loadProducts(false); } function toggleSelected(key: string, checked: boolean) { const next = new Set(selectedKeys.value); if (checked) next.add(key); else next.delete(key); selectedKeys.value = next; }
onMounted(loadSources); async function loadSources() { try { sources.value = await runTelefunc(() => onListSupplierSources()); if (!sourceKey.value && sources.value[0]) sourceKey.value = sourceKeyOf(sources.value[0]); await loadBindingCount(); } catch (cause) { error.value = userErrorMessage(cause); } }
async function loadProducts(forceRefresh = false) { if (!selectedSource.value) return; const requestId = ++catalogRequestId.value; loading.value = true; try { const upstream = await runTelefunc(() => onListSupplierProducts({ provider: selectedSource.value!.provider, normalizedApiOrigin: selectedSource.value!.normalizedApiOrigin, protocolVersion: selectedSource.value!.protocolVersion, page: page.value, forceRefresh }), { notifyError: requestId === catalogRequestId.value }); if (requestId !== catalogRequestId.value) return; totalProducts.value = upstream.total; products.value = upstream.products.flatMap((product) => product.skus.map((sku) => ({ ...product, key: `${product.id}:${sku.id}`, skuId: sku.id, skuName: sku.name, costMinor: sku.costMinor, retailPriceMinor: sku.retailPriceMinor, memberPriceMinor: sku.memberPriceMinor, livePurchasePriceMinor: sku.livePurchasePriceMinor, stockQuantity: sku.stockQuantity, active: product.active && sku.active, localProductName: sku.localProductName }))); catalogLoaded.value = true; selectedKeys.value = new Set([...selectedKeys.value].filter((key) => products.value.some((row) => row.key === key))); } catch (cause) { if (requestId === catalogRequestId.value) { products.value = []; selectedKeys.value = new Set(); error.value = userErrorMessage(cause); } } finally { if (requestId === catalogRequestId.value) loading.value = false; } }
function sync() { if (bindingCount.value) syncDialogOpen.value = true; } async function confirmSync() { const source = selectedSource.value; if (!source || loading.value || syncing.value) return; syncing.value = true; try { const result = await runTelefunc(() => onSyncSupplierSource(sourceInput(source)), { successMessage: "已导入商品同步完成。" }); syncDialogOpen.value = false; lastSyncedAt.value = new Intl.DateTimeFormat("zh-CN", { dateStyle: "short", timeStyle: "short" }).format(new Date()); lastSyncResult.value = `本次已处理 ${result.updated} / ${result.bindingCount} 个 SKU`; await loadBindingCount(); } finally { syncing.value = false; } } function importSelected() { if (selectedKeys.value.size) requestMarkup(products.value.filter((row) => selectedKeys.value.has(row.key))); } function requestMarkup(rows: Product[]) { markupRows.value = rows; fixedMarkupYuan.value = "0"; markupPercent.value = "0"; markupError.value = null; markupDialogOpen.value = true; } async function submitMarkup() { const fixedMarkupText = fixedMarkupYuan.value.trim(); const percentText = markupPercent.value.trim(); const fixedMarkup = parseAmountToCents(fixedMarkupText); const percent = Number(percentText); if (fixedMarkup === null || !/^[0-9]+(?:\.[0-9]{1,2})?$/.test(fixedMarkupText) || !Number.isFinite(percent) || percent < 0 || percent > 100 || !/^[0-9]+(?:\.[0-9]{1,2})?$/.test(percentText)) { markupError.value = "请输入有效的加价金额和比例（0 至 100）。"; return; } const markup = { fixedMarkupMinor: String(fixedMarkup), markupBps: Math.round(percent * 100) }; importingKey.value = markupRows.value.length > 1 ? "batch" : markupRows.value[0]?.key ?? ""; try { const groups = new Map<string, Product[]>(); for (const row of markupRows.value) groups.set(row.id, [...(groups.get(row.id) ?? []), row]); for (const group of groups.values()) await importRows(group, markup); selectedKeys.value = new Set(); markupDialogOpen.value = false; await loadProducts(); } catch (cause) { error.value = userErrorMessage(cause); } finally { importingKey.value = ""; } } async function importRows(rows: Product[], markup: { fixedMarkupMinor: string; markupBps: number }) { const source = selectedSource.value; if (!source || !rows[0]) return; await runTelefunc(() => onImportSupplierProduct({ provider: source.provider, normalizedApiOrigin: source.normalizedApiOrigin, protocolVersion: source.protocolVersion, page: page.value, productId: rows[0].id, skuIds: rows.map((row) => row.skuId), ...markup, publish: false }), { successMessage: "已导入本地商品。" }); } function importSku(row: Product) { if (!importingKey.value) requestMarkup(products.value.filter((item) => item.id === row.id)); }
</script>
